package com.mideas.rpg.v2.game.guild;

public enum MemberSort {

	NAME_ASCENDING,
	NAME_DESCENDING,
	AREA_ASCENDING,
	AREA_DESCENDING,
	LEVEL_ASCENDING,
	LEVEL_DESCENDING,
	CLASS_ASCENDING,
	CLASS_DESCENDING,
	RANK_ASCENDING,
	RANK_DESCENDING,
	NOTE_ASCENDING,
	NOTE_DESCENDING,
	ONLINE_ASCENDING,
	ONLINE_DESCENDING;

}
