package com.mideas.rpg.v2.render;

import java.util.Random;

public class Sprites {

	private static boolean spriteLoaded;
	public static Texture loading_screen;
	public static Texture stuff_hover2;
	public static Texture playerUI;
	public static Texture admin_panel;
	public static Texture hover;
	public static Texture bag_hover2;
	public static Texture close_bag_button;
	public static Texture close_bag_button_hover;
	public static Texture un_green_talent;
	public static Texture deux_green_talent;
	public static Texture trois_green_talent;
	public static Texture quatre_green_talent;
	public static Texture trois_yellow_square_talent;
	public static Texture cinq_yellow_square_talent;
	public static Texture deux_yellow_square_talent;
	public static Texture left_second_line_talent;
	public static Texture cinq_green_talent;
	public static Texture spell_hover;
	public static Texture spell_hover2;
	public static Texture current_bg;
	public static Texture bg;
	public static Texture bc_bg;
	public static Texture doge_bg;
	public static Texture sunwell1_bg;
	public static Texture sunwell2_bg;
	public static Texture illidan_bg;
	public static Texture resized_base_bg;
	public static Texture resized_doge_bg;
	public static Texture resized_bc_bg;
	public static Texture resized_sunwell1_bg;
	public static Texture resized_sunwell2_bg;
	public static Texture resized_illidan_bg;
	public static Texture bag_open_border;
	public static Texture spell_border;
	public static Texture illidan;
	public static Texture priest;
	public static Texture priest2;
	public static Texture mage;
	public static Texture mage2;
	public static Texture war;
	public static Texture war2;
	public static Texture deathknight;
	public static Texture deathknight2;
	public static Texture hunter;
	public static Texture hunter2;
	public static Texture monk;
	public static Texture monk2;
	public static Texture paladin;
	public static Texture paladin2;
	public static Texture rogue;
	public static Texture rogue2;
	public static Texture shaman;
	public static Texture shaman2;
	public static Texture warlock;
	public static Texture warlock2;
	public static Texture playerUI2;
	public static Texture deathknight_create_classe;
	public static Texture hunter_create_classe;
	public static Texture mage_create_classe;
	public static Texture monk_create_classe;
	public static Texture paladin_create_classe;
	public static Texture priest_create_classe;
	public static Texture rogue_create_classe;
	public static Texture shaman_create_classe;
	public static Texture warlock_create_classe;
	public static Texture warrior_create_classe;
	public static Texture deathknight_create_classe_level;
	public static Texture hunter_create_classe_level;
	public static Texture mage_create_classe_level;
	public static Texture monk_create_classe_level;
	public static Texture paladin_create_classe_level;
	public static Texture priest_create_classe_level;
	public static Texture rogue_create_classe_level;
	public static Texture shaman_create_classe_level;
	public static Texture warlock_create_classe_level;
	public static Texture warrior_create_classe_level;
	public static Texture button;
	public static Texture button2;
	public static Texture button_down;
	public static Texture button_hover;
	public static Texture button_hover2;
	public static Texture button_disabled;
	public static Texture new_button;
	public static Texture new_button_down;
	public static Texture new_button_hover;
	public static Texture new_button_disabled;
	public static Texture tooltip;
	public static Texture cursor;
	public static Texture cursor_buy;
	public static Texture alert;
	public static Texture alert_dungeon;
	public static Texture character_frame;
	public static Texture character_frame2;
	public static Texture character_frame_stats;
	public static Texture shop_frame;
	public static Texture class_choose;
	public static Texture bag_hover;
	public static Texture bag_border1;
	public static Texture bag_click_hover;
	public static Texture inventory_click_hover;
	public static Texture gem_red;
	public static Texture gem_blue;
	public static Texture gem_yellow;
	public static Texture gem_meta;
	public static Texture bag4;
	public static Texture bag6;
	public static Texture bag8;
	public static Texture bag10;
	public static Texture bag12;
	public static Texture bag14;
	public static Texture bag16;
	public static Texture bag18;
	public static Texture bag20;
	public static Texture back_bag;
	public static Texture back_bag2;
	public static Texture back_bag3;
	public static Texture back_bag4;
	public static Texture icon_bag;
	public static Texture large_spellbar;
	public static Texture spellbar;
	public static Texture spell_attack;
	public static Texture spell_book_heroic_strike;
	public static Texture spell_book_charge;
	public static Texture spell_book_mortal_strike;
	public static Texture spell_book_thunder_clap;
	public static Texture spell_book_rend;
	public static Texture spell_book_grey_charge;
	public static Texture spell_book_grey_mortal_strike;
	public static Texture spell_book_grey_thunder_clap;
	public static Texture spell_book_grey_rend;
	public static Texture border;
	public static Texture border2;
	public static Texture border3;
	public static Texture border4;
	public static Texture border5;
	public static Texture border6;
	public static Texture border7;
	public static Texture border8;
	public static Texture border9;
	public static Texture border10;
	public static Texture close_button_inventory_hover;
	public static Texture close_button_inventory_down;
	public static Texture close_button_inventory_down_hover;
	public static Texture close_shop_hover;
	public static Texture close_bag_button_down;
	public static Texture close_bag_button_down_hover;
	public static Texture shop_hover;
	public static Texture stuff_border;
	public static Texture stuff_hover;
	public static Texture draggedspell_border;
	public static Texture super_healing_potion;
	public static Texture bag_super_healing_potion;
	public static Texture shop_super_healing_potion;
	public static Texture left_colored_arrow;
	public static Texture right_colored_arrow;
	public static Texture right_uncolored_arrow;
	public static Texture right_arrow_hover;
	public static Texture left_arrow_hover;
	public static Texture gold_coin;
	public static Texture gold_coin_container;
	public static Texture silver_coin;
	public static Texture silver_coin_container;
	public static Texture copper_coin;
	public static Texture copper_coin_container;
	public static Texture warrior_talent_tree;
	public static Texture escape_frame;
	public static Texture level;
	public static Texture spellbook_page1;
	public static Texture spellbook_spell_bg;
	public static Texture spellbook_spell_bg_grey;
	public static Texture close_spell_book_hover;
	public static Texture linen_cloth;
	public static Texture bag_linen_cloth;
	public static Texture craft_frame;
	public static Texture elevator_button;
	public static Texture shop_border;
	public static Texture chat_button;
	public static Texture up_chat_button;
	public static Texture final_spellbar;
	public static Texture spellbar_case;
	public static Texture spellbar_case2;
	public static Texture equipped_item_frame;
	public static Texture shortcut_hover;
	public static Texture bag_hover_tooltip;
	public static Texture loading_screen_bar1;
	public static Texture itemnumber_frame;
	public static Texture itemnumber_hover_ok;
	public static Texture itemnumber_hover_cancel;
	public static Texture itemnumber_leftyellow_arrow;
	public static Texture itemnumber_rightgray_arrow;
	public static Texture loading_screen_bar2;
	public static Texture loading_screen_bar3;
	public static Texture loading_screen_bar4;
	public static Texture loading_screen_bar5;
	public static Texture loading_screen_bar6;
	public static Texture crimson_spinel;
	public static Texture empyrean_sapphire;
	public static Texture pyrestone;
	public static Texture gem_frame;
	public static Texture select_screen_background;
	public static Texture enter_game_colored;
	public static Texture create_new_character_hover;
	public static Texture create_character_background;
	public static Texture login_screen;
	public static Texture selected_character;
	public static Texture button_down_hover;
	public static Texture select_screen_warrior;
	public static Texture select_screen_mage;
	public static Texture select_screen_warlock;
	public static Texture select_screen_shaman;
	public static Texture select_screen_hunter;
	public static Texture select_screen_druid;
	public static Texture select_screen_rogue;
	public static Texture select_screen_priest;
	public static Texture select_screen_paladin;
	public static Texture select_screen_hover;
	public static Texture exp_bar;
	public static Texture life_bar;
	public static Texture mana_bar;
	public static Texture big_alert;
	public static Texture input_box;
	public static Texture top_left_corner_alert;
	public static Texture top_right_corner_alert;
	public static Texture bot_left_corner_alert;
	public static Texture bot_right_corner_alert;
	public static Texture width_top_border_alert;
	public static Texture width_bot_border_alert;
	public static Texture height_left_border_alert;
	public static Texture height_right_border_alert;
	public static Texture reduce_category_craft;
	public static Texture expand_category_craft;
	public static Texture craft_orange_selection;
	public static Texture craft_yellow_selection;
	public static Texture craft_green_selection;
	public static Texture craft_grey_selection;
	public static Texture reduce_category_craft_hover;
	public static Texture expand_category_craft_hover;
	public static Texture scrollbar_up_arrow;
	public static Texture scrollbar_up_arrow_down;
	public static Texture scrollbar_grey_up_arrow;
	public static Texture scrollbar_down_arrow;
	public static Texture scrollbar_down_arrow_down;
	public static Texture scrollbar_grey_down_arrow;
	public static Texture scrollbar_arrow_hover;
	public static Texture ascensor;
	public static Texture profession_border;
	public static Texture scrollbar;
	public static Texture top_button;
	public static Texture bot_button;
	public static Texture cast_bar;
	public static Texture cast_bar_progression;
	public static Texture cast_bar_glow;
	public static Texture loading_screen_bar;
	public static Texture loading_screen_bar_progress;
	public static Texture check_box;
	public static Texture check_box_hover;
	public static Texture check_box_down;
	public static Texture check_box_down_hover;
	public static Texture check_box_enable;
	public static Texture check_box_disable;
	public static Texture interface_option_frame;
	public static Texture socketing_frame;
	public static Texture cross_button;
	public static Texture cross_button_hover;
	public static Texture cross_button_down;
	public static Texture cross_button_hover_down;
	public static Texture empty_blue_cross;
	public static Texture empty_red_cross;
	public static Texture empty_yellow_cross;
	public static Texture filled_blue_cross;
	public static Texture filled_red_cross;
	public static Texture filled_yellow_cross;
	public static Texture red_socket_background;
	public static Texture blue_socket_background;
	public static Texture yellow_socket_background;
	public static Texture trade_frame;
	public static Texture click_down;
	public static Texture trade_accepted;
	public static Texture realm_list_background;
	public static Texture realm_list_box;
	public static Texture selected_realm;
	public static Texture friend_frame;
	public static Texture friend_border;
	public static Texture friend_note_online;
	public static Texture friend_note;
	public static Texture friend_note_offline;
	public static Texture party_leader_crown;
	public static Texture player_portrait_party;
	public static Texture party_tooltip;
	public static Texture tooltip_bot;
	public static Texture tooltip_top;
	public static Texture tooltip_left;
	public static Texture tooltip_right;
	public static Texture tooltip_top_left_corner;
	public static Texture tooltip_top_right_corner;
	public static Texture tooltip_bot_left_corner;
	public static Texture tooltip_bot_right_corner;
	public static Texture input_bar_left_border;
	public static Texture input_bar_middle_border;
	public static Texture input_bar_right_border;
	public static Texture text_menu_hover;
	public static Texture button_menu_selected_left;
	public static Texture button_menu_selected_right;
	public static Texture button_menu_selected_middle;
	public static Texture button_menu_unselected_left;
	public static Texture button_menu_unselected_right;
	public static Texture button_menu_unselected_middle;
	public static Texture button_menu_unselected_top;
	public static Texture button_menu;
	public static Texture button_menu_hover;
	public static Texture guild_frame;
	public static Texture guild_close_information_button_border;
	public static Texture guild_member_display_button_border;
	public static Texture edit_box_left_border;
	public static Texture edit_box_middle_border;
	public static Texture edit_box_right_border;
	public static Texture arrow_top_down;
	public static Texture arrow_top;
	public static Texture arrow_right_down;
	public static Texture arrow_right;
	public static Texture arrow_right_disabled;
	public static Texture arrow_left_down;
	public static Texture arrow_left;
	public static Texture arrow_left_disabled;
	public static Texture arrow_bot_down;
	public static Texture arrow_bot;
	public static Texture arrow_hover;
	public static Texture drop_down_menu_left_border;
	public static Texture drop_down_menu_middle_border;
	public static Texture drop_down_menu_right_border;
	public static Texture horizontal_bar_left;
	public static Texture horizontal_bar_middle;
	public static Texture horizontal_bar_right;
	public static Texture guild_manage_frame_bot_border;
	public static Texture guild_manage_rank_horizontal_bar;
	public static Texture button_menu_sort_left_part;
	public static Texture button_menu_sort_middle_part;
	public static Texture button_menu_sort_right_part;
	public static Texture frame_tab_active_left_part;
	public static Texture frame_tab_active_middle_part;
	public static Texture frame_tab_active_right_part;
	public static Texture frame_tab_inactive_left_part;
	public static Texture frame_tab_inactive_middle_part;
	public static Texture frame_tab_inactive_right_part;
	public static Texture ignore_frame;
	public static Texture tooltip_frame;
	public static Texture alert_background;
	public static Texture who_frame;
	public static Texture mlg_frog;
	public static Texture alert_title_left_border;
	public static Texture alert_title_middle_border;
	public static Texture alert_title_right_border;
	public static Texture button_down_spellbar;
	public static Texture button_hover_spellbar;
	public static Texture chat_logo_blizz;
	public static Texture chat_channel_button;
	public static Texture discussion_frame;
	public static Texture auction_browse_frame;
	public static Texture auction_bids_frame;
	public static Texture auction_auctions_frame;
	public static Texture auction_browse_item_left_border;
	public static Texture auction_browse_item_middle_border;
	public static Texture auction_browse_item_right_border;
	public static Texture edit_box_cross_button;
	public static Texture edit_box_cross_button_hover;
	public static Texture edit_box;
	public static Texture button_menu_sort;
	public static Texture mail_inbox_frame;
	public static Texture mail_opened_mail_frame;
	public static Texture mail_send_mail_frame;
	public static Texture frame_tab_active2;
	public static Texture frame_tab_not_active2;
	public static Texture frame_tab_not_hover2;
	public static Texture new_cross_button;
	public static Texture new_cross_button_down;
	public static Texture new_cross_button_hover;
	public static Texture[] shortcut = new Texture[8];
	private static String easternKingdom = "sprite/interface/loading_screen/LoadScreenEasternKingdom2.png";
	private static String outland2 = "sprite/interface/loading_screen/LOADSCREENOUTLAND2WIDE.png";
	private static String outland = "sprite/interface/loading_screen/LoadScreenOutlandWide.png";
	
	private static String[] bgList = new String[3];
	
	public static void initBG() {
		bgList[0] = easternKingdom;
		bgList[1] = outland2;
		bgList[2] = outland;
		loading_screen = new Texture(bgList[new Random().nextInt((bgList.length-1)+1)], true, true);
		loading_screen_bar = new Texture("sprite/interface/loading_screen/Loading-BarBorder.png", true, true);
		loading_screen_bar_progress = new Texture("sprite/interface/loading_screen/Loading-BarFill.png", true, true);
	}
	
	public static boolean sprite() {
		gem_frame = new Texture("sprite/interface/gem/gem_frame.png", false);
		pyrestone = new Texture("sprite/gem/inv_jewelcrafting_pyrestone_02.jpg", false);
		empyrean_sapphire = new Texture("sprite/gem/inv_jewelcrafting_empyreansapphire_02.jpg", false);
		crimson_spinel = new Texture("sprite/gem/inv_jewelcrafting_crimsonspinel_02.jpg", false);
		gem_red = new Texture("sprite/interface/gem/gem_red.png", false);
		gem_blue = new Texture("sprite/interface/gem/gem_blue.png", false);
		gem_yellow = new Texture("sprite/interface/gem/gem_yellow.png", false);
		gem_meta = new Texture("sprite/interface/gem/gem_meta.png", false);
		close_bag_button_down = new Texture("sprite/interface/buttons/close_button_bag_down.png", false);
		close_bag_button_down_hover = new Texture("sprite/interface/buttons/close_button_bag_down_hover.png", false);
		itemnumber_leftyellow_arrow = new Texture("sprite/interface/itemnumber_leftyellow_arrow.png", false);
		itemnumber_rightgray_arrow = new Texture("sprite/interface/itemnumber_rightgray_arrow.png", false);
		equipped_item_frame = new Texture("sprite/interface/equipped_item_frame.png", false);
		itemnumber_hover_ok = new Texture("sprite/interface/itemnumber_hover_ok.png", false);
		itemnumber_hover_cancel = new Texture("sprite/interface/itemnumber_hover_cancel.png", false);
		itemnumber_frame = new Texture("sprite/interface/itemnumber_frame.png", false);
		shortcut_hover = new Texture("sprite/interface/shotcut_hover.png", false);
		close_bag_button = new Texture("sprite/interface/buttons/close_button_bag.png", false);
		close_bag_button_hover = new Texture("sprite/interface/buttons/close_button_bag_hover.png", false);
		bag_hover_tooltip = new Texture("sprite/interface/bag_hover_tooltip.png", false);
		elevator_button = new Texture("sprite/interface/elevator_button.png", false);
		bag_click_hover = new Texture("sprite/interface/bag_click_hover.png", false);
		inventory_click_hover = new Texture("sprite/interface/inventory_click_hover.png", false);
		bag_open_border = new Texture("sprite/interface/bag_open_border.png", false);
		shortcut[0] = new Texture("sprite/interface/shortcut/character_frame_open.png", false);
		shortcut[1] = new Texture("sprite/interface/shortcut/book_frame_open.png", false);
		shortcut[2] = new Texture("sprite/interface/shortcut/talent_frame_open.png", false);
		//shortcut[3] = quest_open
		shortcut[4] = new Texture("sprite/interface/shortcut/social_frame_open.png", false);
		//shortcut[5] = lfg_open
		shortcut[6] = new Texture("sprite/interface/shortcut/escape_frame_open.png", false);
		//shortcut[7] = request_open
		edit_box_left_border = new Texture("sprite/interface/edit_box/left_border_good.png", true);
		spellbar_case = new Texture("sprite/interface/UI-Quickslot.png", false);
		spellbar_case2 = new Texture("sprite/interface/UI-Quickslot.png", false);
		final_spellbar = new Texture("sprite/interface/very_final_spellbar.png", false);
		up_chat_button = new Texture("sprite/interface/up_chat_button.png", false);
		chat_button = new Texture("sprite/interface/chat/chat_button.png", false);
		craft_frame = new Texture("sprite/interface/profession/craft_frame.png", false);
		linen_cloth = new Texture("sprite/items/craft/linen_cloth.jpg", false);
		bag_linen_cloth = new Texture("sprite/items/bagcraft/bag_linen_cloth.jpg", false);
		admin_panel = new Texture("sprite/interface/admin_panel.png", false);
		current_bg = new Texture("sprite/interface/bg.png", false);
		doge_bg = new Texture("sprite/interface/bgDoge.jpg", false);
		doge_bg = new Texture("sprite/interface/bgDoge.jpg", false);
		bg = new Texture("sprite/interface/bg.png", false);
		bc_bg = new Texture("sprite/interface/bc_bg.jpg", false);
		illidan_bg = new Texture("sprite/interface/illidan_bg.jpg", false);
		sunwell1_bg = new Texture("sprite/interface/sunwell1_bg.jpg", false);
		sunwell2_bg = new Texture("sprite/interface/sunwell2_bg.jpg", false);
		resized_base_bg = new Texture("sprite/interface/resizedBG/resized_base_bg.png", false);
		resized_doge_bg = new Texture("sprite/interface/resizedBG/resized_doge_bg.png", false);
		resized_bc_bg = new Texture("sprite/interface/resizedBG/resized_bc_bg.png", false);
		resized_sunwell1_bg = new Texture("sprite/interface/resizedBG/resized_sunwell1_bg.png", false);
		resized_sunwell2_bg = new Texture("sprite/interface/resizedBG/resized_sunwell2_bg.png", false);
		resized_illidan_bg = new Texture("sprite/interface/resizedBG/resized_illidan_bg.png", false);
		close_spell_book_hover = new Texture("sprite/interface/buttons/close_spell_book_hover.png", false);
		spellbook_page1 = new Texture("sprite/interface/spell/spellbook.png", false);
		spellbook_spell_bg = new Texture("sprite/interface/spell/spellbook_spell_bg.png", false);
		spellbook_spell_bg_grey = new Texture("sprite/interface/spell/spellbook_spell_bg_grey.png", false);
		escape_frame = new Texture("sprite/interface/optionFrame.png", false);
		level = new Texture("sprite/interface/level.png", false);
		un_green_talent = new Texture("sprite/interface/talent/1_green_talent.png", false);
		deux_green_talent = new Texture("sprite/interface/talent/2_green_talent.png", false);
		trois_green_talent = new Texture("sprite/interface/talent/3_green_talent.png", false);
		gold_coin_container = new Texture("sprite/interface/gold_coin_container.png", false);
		party_leader_crown = new Texture("sprite/interface/party/party_leader_crown.png", false);
		player_portrait_party = new Texture("sprite/interface/party/player_portrait_party.png", false);
		party_tooltip = new Texture("sprite/interface/party/tooltip.png", false);
		text_menu_hover = new Texture("sprite/interface/UI-Listbox-Highlight.png", false);
		arrow_top = new Texture("sprite/interface/arrow/UI-ChatIcon-ScrollUp-Up.png", false);
		arrow_top_down = new Texture("sprite/interface/arrow/UI-ChatIcon-ScrollUp-Down.png", false);
		arrow_bot = new Texture("sprite/interface/arrow/UI-ChatIcon-ScrollDown-Up.png", false);
		arrow_bot_down = new Texture("sprite/interface/arrow/UI-ChatIcon-ScrollDown-Down.png", false);
		arrow_right = new Texture("sprite/interface/arrow/UI-SpellbookIcon-NextPage-Up.png", false);
		arrow_right_disabled = new Texture("sprite/interface/arrow/UI-SpellbookIcon-NextPage-Disabled.png", false);
		arrow_right_down = new Texture("sprite/interface/arrow/UI-SpellbookIcon-NextPage-Down.png", false);
		arrow_left = new Texture("sprite/interface/arrow/UI-SpellbookIcon-PrevPage-Up.png", false);
		arrow_left_disabled = new Texture("sprite/interface/arrow/UI-SpellbookIcon-PrevPage-Disabled.png", false);
		arrow_left_down = new Texture("sprite/interface/arrow/UI-SpellbookIcon-PrevPage-Down.png", false);
		arrow_hover = new Texture("sprite/interface/arrow/UI-Common-MouseHilight.png", false);
		drop_down_menu_left_border = new Texture("sprite/interface/drop_down_menu/left_border.png", false);
		drop_down_menu_middle_border = new Texture("sprite/interface/drop_down_menu/middle_border.png", false);
		drop_down_menu_right_border = new Texture("sprite/interface/drop_down_menu/right_border.png", false);
		guild_manage_frame_bot_border = new Texture("sprite/interface/social/guild_manage_frame_bot_border.png", false);
		guild_manage_rank_horizontal_bar = new Texture("sprite/interface/social/guild_manage_rank_horizontal_bar.png", false);
		tooltip_frame = new Texture("sprite/interface/tooltip/tooltip.png", true);
		alert_background = new Texture("sprite/interface/alert_background/alert_background.png", true);
		mlg_frog = new Texture("sprite/interface/hqdefault.png", false);
		alert_title_left_border = new Texture("sprite/interface/alert_background/title_left_border.png", true);
		alert_title_middle_border = new Texture("sprite/interface/alert_background/title_middle_border.png", true);
		alert_title_right_border = new Texture("sprite/interface/alert_background/title_right_border.png", true);
		button_down_spellbar = new Texture("sprite/interface/click_down.png", false);
		button_hover_spellbar = new Texture("sprite/interface/OldButtonHilight-Square.png", false);
		chat_logo_blizz = new Texture("sprite/interface/chat/blizzard_logo.png", false);
		chat_channel_button = new Texture("sprite/interface/social/UI-AuctionFrame-FilterBg.png", false);
		edit_box_cross_button = new Texture("sprite/interface/edit_box/cross_button.png", false);
		edit_box_cross_button_hover = new Texture("sprite/interface/edit_box/cross_button_hover.png", false);
		button_menu_sort = new Texture("sprite/interface/button_menu_sort/button_menu_sort.png", false);
		auction_browse_item_left_border = new Texture("sprite/interface/auction/browse_item_left_border.png", false);
		auction_browse_item_middle_border = new Texture("sprite/interface/auction/browse_item_middle_border.png", false);
		auction_browse_item_right_border = new Texture("sprite/interface/auction/browse_item_right_border.png", false);
		mail_inbox_frame = new Texture("sprite/interface/mail/mail_inbox_frame.png", false);
		mail_opened_mail_frame = new Texture("sprite/interface/mail/mail_opened_mail_frame.png", false);
		mail_send_mail_frame = new Texture("sprite/interface/mail/mail_send_mail_frame.png", false);
		frame_tab_active2 = new Texture("sprite/interface/frame_tabv2/frame_tab_selected.png", false);
		frame_tab_not_active2 = new Texture("sprite/interface/frame_tabv2/frame_tab_not_selected.png", false);
		frame_tab_not_hover2 = new Texture("sprite/interface/frame_tabv2/UI-Character-Tab-RealHighlight.png", false);
		return true;
	}
	
	public static boolean sprite2() {
		select_screen_background = new Texture("sprite/selectScreen/select_screen_background.png", true);
		enter_game_colored = new Texture("sprite/selectScreen/enter_game_colored.png", true);
		create_new_character_hover = new Texture("sprite/selectScreen/create_new_character_hover.png", true);
		create_character_background = new Texture("sprite/selectScreen/create_character_background.png", true);
		draggedspell_border = new Texture("sprite/interface/draggedspell_border.png", false);
		mage = new Texture("sprite/classes/mage.png", true);
		//mage2 = new Texture("sprite/classes/mage.png", true);
		war = new Texture("sprite/classes/warrior.png", true);
		//war2 = new Texture("sprite/classes/warrior.png", true);
		deathknight = new Texture("sprite/classes/death_knight.png", true);
		//deathknight2 = new Texture("sprite/classes/death_knight.png", true);
		hunter = new Texture("sprite/classes/hunter.png", true);
		//hunter2 = new Texture("sprite/classes/hunter.png", true);
		monk = new Texture("sprite/classes/monk.png", true);
		//monk2 = new Texture("sprite/classes/monk.png", true);
		paladin = new Texture("sprite/classes/paladin.png", true);
		//paladin2 = new Texture("sprite/classes/paladin.png", true);
		rogue = new Texture("sprite/classes/rogue.png", true);
		//rogue2 = new Texture("sprite/classes/rogue.png", true);
		shaman = new Texture("sprite/classes/shaman.png", true);
		//shaman2= new Texture("sprite/classes/shaman.png", true);
		warlock = new Texture("sprite/classes/warlock.png", true);
		//warlock2 = new Texture("sprite/classes/warlock.png", true);

		deathknight_create_classe = new Texture("sprite/createClasses/death_knight_createClasse.jpg", false);
		hunter_create_classe = new Texture("sprite/createClasses/hunter_createClasse.jpg", false);
		mage_create_classe = new Texture("sprite/createClasses/mage_createClasse.jpg", false);
		monk_create_classe = new Texture("sprite/createClasses/monk_createClasse.jpg", false);
		paladin_create_classe = new Texture("sprite/createClasses/paladin_createClasse.jpg", false);
		priest_create_classe = new Texture("sprite/createClasses/priest_createClasse.jpg", false);
		rogue_create_classe = new Texture("sprite/createClasses/rogue_createClasse.jpg", false);
		shaman_create_classe = new Texture("sprite/createClasses/shaman_createClasse.jpg", false);
		warlock_create_classe = new Texture("sprite/createClasses/warlock_createClasse.jpg", false);
		warrior_create_classe = new Texture("sprite/createClasses/warrior_createClasse.jpg", false);
		
		deathknight_create_classe_level = new Texture("sprite/createClasses/death_knight_level.jpg", false);
		hunter_create_classe_level = new Texture("sprite/createClasses/hunter_level.jpg", false);
		mage_create_classe_level = new Texture("sprite/createClasses/mage_level.jpg", false);
		monk_create_classe_level = new Texture("sprite/createClasses/monk_level.jpg", false);
		paladin_create_classe_level = new Texture("sprite/createClasses/paladin_level.jpg", false);
		priest_create_classe_level = new Texture("sprite/createClasses/priest_level.jpg", false);
		rogue_create_classe_level = new Texture("sprite/createClasses/rogue_level.jpg", false);
		shaman_create_classe_level = new Texture("sprite/createClasses/shaman_level.jpg", false);
		warlock_create_classe_level = new Texture("sprite/createClasses/warlock_level.jpg", false);
		warrior_create_classe_level = new Texture("sprite/createClasses/warrior_level.jpg", false);

		select_screen_warrior = new Texture("sprite/selectScreen/warrior.png", true);
		select_screen_paladin = new Texture("sprite/selectScreen/paladin.png", true);
		select_screen_mage = new Texture("sprite/selectScreen/mage.png", true);
		select_screen_warlock = new Texture("sprite/selectScreen/warlock.png", true);
		select_screen_shaman = new Texture("sprite/selectScreen/shaman.png", true);
		select_screen_priest = new Texture("sprite/selectScreen/priest.png", true);
		select_screen_rogue = new Texture("sprite/selectScreen/rogue.png", true);
		select_screen_druid = new Texture("sprite/selectScreen/druid.png", true);
		select_screen_hunter = new Texture("sprite/selectScreen/hunter.png", true);
		select_screen_hover = new Texture("sprite/selectScreen/hover.png", true);
		large_spellbar = new Texture("sprite/interface/large_spellbar.png", true);
		silver_coin = new Texture("sprite/interface/silver_coin.png", false);
		silver_coin_container = new Texture("sprite/interface/silver_coin_container.png", false);
		copper_coin = new Texture("sprite/interface/copper_coin.png", false);
		copper_coin_container = new Texture("sprite/interface/copper_coin_container.png", false);
		right_arrow_hover = new Texture("sprite/interface/right_arrow_hover.jpg", false);
		left_arrow_hover = new Texture("sprite/interface/left_arrow_hover.jpg", false);
		warrior_talent_tree = new Texture("sprite/interface/talent/warrior_talent_tree.png", false);
		playerUI = new Texture("sprite/interface/UI-Player-Portrait.png", false);
		playerUI2 = new Texture("sprite/interface/UI-Player-Portrait.png", false);
		illidan = new Texture("sprite/classes/illidan.png", false);
		priest = new Texture("sprite/classes/priest.png", false);
		//priest2 = new Texture("sprite/classes/priest.png");
		trade_accepted = new Texture("sprite/interface/trade/trade_accepted.png", false);
		stuff_border = new Texture("sprite/interface/stuff_border.png", false);
		realm_list_background = new Texture("sprite/interface/realm_list/realm_list_background.png", true);
		realm_list_box = new Texture("sprite/interface/realm_list/realm_list_box.png", true);
		selected_realm = new Texture("sprite/interface/realm_list/selected_realm.png", true);
		input_bar_left_border = new Texture("sprite/interface/chat/UI-ChatInputBorder-Left2.png", true);
		input_bar_middle_border = new Texture("sprite/interface/chat/UI-ChatInputBorder-Mid.png", true);
		input_bar_right_border = new Texture("sprite/interface/chat/UI-ChatInputBorder-Right2.png", true);
		horizontal_bar_left = new Texture("sprite/interface/horizontal_bar/left_part.png", true);
		horizontal_bar_middle = new Texture("sprite/interface/horizontal_bar/middle_part.png", true);
		horizontal_bar_right = new Texture("sprite/interface/horizontal_bar/right_part.png", true);
		who_frame = new Texture("sprite/interface/social/who_frame.png", false);
		auction_browse_frame = new Texture("sprite/interface/auction/browse_frame.png", false);
		auction_bids_frame = new Texture("sprite/interface/auction/bids_frame.png", false);
		auction_auctions_frame = new Texture("sprite/interface/auction/auctions_frame.png", false);
		return true;
	}
		
	public static boolean sprite8() {
		bag_super_healing_potion = new Texture("sprite/items/bagpotion/bag_super_healing_potion.jpg", false);
		shop_super_healing_potion = new Texture("sprite/items/shoppotion/shop_super_healing_potion.jpg", false);
		super_healing_potion = new Texture("sprite/items/potion/super_healing_potion.jpg", false);

		bag_border1 = new Texture("sprite/interface/bag_border.png", false);
		shop_border = new Texture("sprite/interface/shop_border.png", false);
		
		//bot_left_corner_alert = new Texture("sprite/interface/alert_background/bot_left_corner_alert.png", true);
		//bot_right_corner_alert = new Texture("sprite/interface/alert_background/bot_right_corner_alert.png", true);
		top_left_corner_alert = new Texture("sprite/interface/alert_background/top_left_corner_alert.png", true);
		/*top_right_corner_alert = new Texture("sprite/interface/alert_background/top_right_corner_alert.png", true);
		width_top_border_alert = new Texture("sprite/interface/alert_background/width_top_border_alert.png", true);
		width_bot_border_alert = new Texture("sprite/interface/alert_background/width_bot_border_alert.png", true);
		height_left_border_alert = new Texture("sprite/interface/alert_background/height_left_border_alert.png", true);
		height_right_border_alert = new Texture("sprite/interface/alert_background/height_right_border_alert.png", true);*/
		reduce_category_craft = new Texture("sprite/interface/buttons/reduce_craft_category.png", false);
		expand_category_craft = new Texture("sprite/interface/buttons/expand_craft_category.png", false);
		reduce_category_craft_hover = new Texture("sprite/interface/buttons/reduce_craft_category_hover.png", false);
		expand_category_craft_hover = new Texture("sprite/interface/buttons/expand_craft_category_hover.png", false);
		craft_orange_selection = new Texture("sprite/interface/profession/craft_orange_selection.png", false);
		craft_yellow_selection = new Texture("sprite/interface/profession/craft_yellow_selection.png", false);
		craft_green_selection = new Texture("sprite/interface/profession/craft_green_selection.png", false);
		craft_grey_selection = new Texture("sprite/interface/profession/craft_grey_selection.png", false);
		scrollbar_up_arrow = new Texture("sprite/interface/scrollBar/UI-ScrollBar-ScrollUpButton-Up.png", false);
		scrollbar_up_arrow_down = new Texture("sprite/interface/scrollBar/UI-ScrollBar-ScrollUpButton-Down.png", false);
		scrollbar_grey_up_arrow = new Texture("sprite/interface/scrollBar/UI-ScrollBar-ScrollUpButton-Disabled.png", false);
		scrollbar_down_arrow = new Texture("sprite/interface/scrollBar/UI-ScrollBar-ScrollDownButton-Up.png", false);
		scrollbar_down_arrow_down = new Texture("sprite/interface/scrollBar/UI-ScrollBar-ScrollDownButton-Down.png", false);
		scrollbar_grey_down_arrow = new Texture("sprite/interface/scrollBar/UI-ScrollBar-ScrollDownButton-Disabled.png", false);
		scrollbar_arrow_hover = new Texture("sprite/interface/scrollBar/UI-ScrollBar-ScrollDownButton-Highlight.png", false);
		ascensor = new Texture("sprite/interface/scrollBar/UI-ScrollBar-Knob.png", false);
		scrollbar = new Texture("sprite/interface/scrollBar/scrollbar_border.png", false);
		top_button = new Texture("sprite/interface/scrollBar/top_button.png", false);
		bot_button = new Texture("sprite/interface/scrollBar/bot_button.png", false);
		profession_border = new Texture("sprite/interface/profession/border.png", false);
		button_disabled = new Texture("sprite/interface/button_disabled.png", true);
		cast_bar = new Texture("sprite/interface/cast/cast_bar.png", false);
		cast_bar_progression = new Texture("sprite/interface/cast/cast_bar_progression.png", false);
		cast_bar_glow = new Texture("sprite/interface/cast/cast_bar_glow.png", false);
		quatre_green_talent = new Texture("sprite/interface/talent/4_green_talent.png", false);
		trois_yellow_square_talent = new Texture("sprite/interface/talent/yellow_3-3_talent.png", false);
		deux_yellow_square_talent = new Texture("sprite/interface/talent/yellow_2-2_talent.png", false);
		cinq_yellow_square_talent = new Texture("sprite/interface/talent/yellow_5-5_talent.png", false);
		left_second_line_talent = new Texture("sprite/interface/talent/left_second_line_talent.png", false);
		left_colored_arrow = new Texture("sprite/interface/left_colored_arrow.png", false);
		right_colored_arrow = new Texture("sprite/interface/right_colored_arrow.png", false);
		right_uncolored_arrow = new Texture("sprite/interface/right_uncolored_arrow.png", false);
		gold_coin = new Texture("sprite/interface/gold_coin.png", false);
		check_box = new Texture("sprite/interface/checkBox/UI-CheckBox-Up.png", true);
		check_box_hover = new Texture("sprite/interface/checkBox/UI-CheckBox-Highlight.png", true);
		check_box_down = new Texture("sprite/interface/checkBox/UI-CheckBox-Down.png", true);
		check_box_enable = new Texture("sprite/interface/checkBox/check_box_enable.png", true);
		check_box_disable = new Texture("sprite/interface/checkBox/UI-CheckBox-Check-Disabled.png", true);
		interface_option_frame = new Texture("sprite/interface/interface_option_frame.png", false);
		socketing_frame = new Texture("sprite/interface/gem/UI-ItemSocketingFrame.png", false);
		cross_button = new Texture("sprite/interface/cross_button/cross_button.png", false);
		cross_button_down = new Texture("sprite/interface/cross_button/cross_button_down.png", false);
		cross_button_hover = new Texture("sprite/interface/cross_button/cross_button_hover.png", false);
		cross_button_hover_down = new Texture("sprite/interface/cross_button/cross_button_hover_down.png", false);
		empty_blue_cross = new Texture("sprite/interface/gem/empty_blue_cross.png", false);
		empty_red_cross = new Texture("sprite/interface/gem/empty_red_cross.png", false);
		empty_yellow_cross = new Texture("sprite/interface/gem/empty_yellow_cross.png", false);
		filled_yellow_cross = new Texture("sprite/interface/gem/filled_yellow_cross.png", false);
		filled_red_cross = new Texture("sprite/interface/gem/filled_red_cross.png", false);
		filled_blue_cross = new Texture("sprite/interface/gem/filled_blue_cross.png", false);
		red_socket_background = new Texture("sprite/interface/gem/red_socket_background.png", false);
		blue_socket_background = new Texture("sprite/interface/gem/blue_socket_background.png", false);
		yellow_socket_background = new Texture("sprite/interface/gem/yellow_socket_background.png", false);
		click_down = new Texture("sprite/interface/click_down.png", false);
		guild_frame = new Texture("sprite/interface/social/guild_frame.png", false);
		guild_close_information_button_border = new Texture("sprite/interface/social/guild_close_information_button_border.png", false);
		guild_member_display_button_border = new Texture("sprite/interface/social/guild_member_display_button_border.png", false);
		edit_box_middle_border = new Texture("sprite/interface/edit_box/middle_border_good.png", true);
		edit_box_right_border = new Texture("sprite/interface/edit_box/right_border_good.png", true);
		edit_box = new Texture("sprite/interface/edit_box/edit_box_good.png", true);
		button_menu_sort_left_part = new Texture("sprite/interface/button_menu_sort/left_part.png", false);
		button_menu_sort_middle_part = new Texture("sprite/interface/button_menu_sort/middle_part.png", false);
		button_menu_sort_right_part = new Texture("sprite/interface/button_menu_sort/right_part.png", false);
		new_cross_button = new Texture("sprite/interface/cross_buttonv2/UI-Panel-MinimizeButton-Up.png", false);
		new_cross_button_down = new Texture("sprite/interface/cross_buttonv2/UI-Panel-MinimizeButton-Down.png", false);
		new_cross_button_hover = new Texture("sprite/interface/cross_buttonv2/UI-Panel-MinimizeButton-Highlight.png", false);
		return true;
	}
		
	public static boolean sprite9() {
		selected_character = new Texture("sprite/interface/Glue-CharacterSelect-Highlight.png", true);
		login_screen = new Texture("sprite/interface/login_screen.png", true);
		bag4 = new Texture("sprite/interface/bag/4.png", false);
		bag6 = new Texture("sprite/interface/bag/6.png", false);
		bag8 = new Texture("sprite/interface/bag/8.png", false);
		bag10 = new Texture("sprite/interface/bag/10.png", false);
		bag12 = new Texture("sprite/interface/bag/12.png", false);
		bag14 = new Texture("sprite/interface/bag/14.png", false);
		bag16 = new Texture("sprite/interface/bag/16.png", false);
		bag18 = new Texture("sprite/interface/bag/18.png", false);
		bag20 = new Texture("sprite/interface/bag/20.png", false);
		back_bag = new Texture("sprite/interface/bag/backbag.png", false);
		icon_bag = new Texture("sprite/interface/icon_bag.png", false);
		bag_hover = new Texture("sprite/interface/bag_hover.png", false);
		bag_hover2 = new Texture("sprite/interface/bag_hover.png", false);
		shop_hover = new Texture("sprite/interface/shop_hover.png", false);
		stuff_hover = new Texture("sprite/interface/stuff_hover.png", false);
		stuff_hover2 = new Texture("sprite/interface/stuff_hover.png", false);
		character_frame = new Texture("sprite/interface/characterFrame_final.png", false);
		character_frame2 = new Texture("sprite/interface/characterFrame.png", false);
		character_frame_stats = new Texture("sprite/interface/character_frame_stats.png", false);
		shop_frame = new Texture("sprite/interface/shop_frame.png", false);
		class_choose = new Texture("sprite/interface/class_choose.png", false);
		border = new Texture("sprite/interface/border.png", false);
		spell_hover = new Texture("sprite/interface/spell_hover.png", false);
		spell_hover2 = new Texture("sprite/interface/spell_hover.png", false);
		spell_border = new Texture("sprite/interface/spell_border.png", false);
		border2 = new Texture("sprite/interface/border.png", false);
		hover = new Texture("sprite/interface/hover.png", false);
		button = new Texture("sprite/interface/button.png", true);
		button2 = new Texture("sprite/interface/button.png", true);
		button_down = new Texture("sprite/interface/button_down.png", true);
		button_hover = new Texture("sprite/interface/button_hover.png", true, false);
		button_hover2 = new Texture("sprite/interface/button_hover.png", true);
		button_down_hover = new Texture("sprite/interface/button_down_hover.png", true);
		new_button = new Texture("sprite/interface/new_button.png", true);
		new_button_down = new Texture("sprite/interface/new_button_down.png", true);
		new_button_hover = new Texture("sprite/interface/new_button_hover.png", true);
		new_button_disabled = new Texture("sprite/interface/new_button_disabled.png", true);
		tooltip = new Texture("sprite/interface/tooltip.png", true);
		cursor = new Texture("sprite/interface/cursor.png", true);
		cursor_buy = new Texture("sprite/interface/cursor_buy.png", false);
		alert = new Texture("sprite/interface/alert.png", true);
		alert_dungeon = new Texture("sprite/interface/alert_dungeon.png", false);
		close_button_inventory_hover = new Texture("sprite/interface/buttons/close_button_inventory_hover.png", false);
		close_button_inventory_down = new Texture("sprite/interface/buttons/close_button_inventory_down.png", false);
		close_button_inventory_down_hover = new Texture("sprite/interface/buttons/close_button_inventory_down_hover.png", false);
		close_shop_hover = new Texture("sprite/interface/buttons/close_shop_hover.png", false);
		exp_bar = new Texture("sprite/interface/exp_bar.png", false);
		life_bar = new Texture("sprite/interface/life_bar.png", false);
		mana_bar = new Texture("sprite/interface/mana_bar.png", false);
		big_alert = new Texture("sprite/interface/big_alert.png", false);
		input_box = new Texture("sprite/interface/input_box.png", true);
		trade_frame = new Texture("sprite/interface/trade/trade_frame.png", false);
		friend_frame = new Texture("sprite/interface/social/friend_frame.png", false);
		ignore_frame = new Texture("sprite/interface/social/ignore_frame.png", false);
		friend_border = new Texture("sprite/interface/social/UI-FriendsFrame-HighlightBar.png", false);
		friend_note_online = new Texture("sprite/interface/social/friend_note_online.png", false);
		friend_note = new Texture("sprite/interface/social/friend_note.png", false);
		friend_note_offline = new Texture("sprite/interface/social/friend_note_offline.png", false);
		tooltip_bot = new Texture("sprite/interface/tooltip/UI-Tooltip-B.png", false);
		tooltip_bot_left_corner = new Texture("sprite/interface/tooltip/UI-Tooltip-BL.png", false);
		tooltip_bot_right_corner = new Texture("sprite/interface/tooltip/UI-Tooltip-BR.png", false);
		tooltip_left = new Texture("sprite/interface/tooltip/UI-Tooltip-L.png", false);
		tooltip_right = new Texture("sprite/interface/tooltip/UI-Tooltip-R.png", false);
		tooltip_top = new Texture("sprite/interface/tooltip/UI-Tooltip-T.png", false);
		tooltip_top_left_corner = new Texture("sprite/interface/tooltip/UI-Tooltip-TL.png", false);
		tooltip_top_right_corner = new Texture("sprite/interface/tooltip/UI-Tooltip-TR.png", false);
		button_menu = new Texture("sprite/interface/button_menu/UI-CHARACTER-INACTIVETAB.png", true);
		button_menu_selected_left = new Texture("sprite/interface/button_menu/selected_menu_left.png", true);
		button_menu_selected_right = new Texture("sprite/interface/button_menu/selected_menu_right.png", true);
		button_menu_selected_middle = new Texture("sprite/interface/button_menu/selected_menu_middle.png", true);
		button_menu_hover = new Texture("sprite/interface/button_menu/UI-Character-Tab-Highlight.png", true);
		button_menu_unselected_left = new Texture("sprite/interface/button_menu/unselected_menu_left.png", true);
		button_menu_unselected_right = new Texture("sprite/interface/button_menu/unselected_menu_right.png", true);
		button_menu_unselected_middle = new Texture("sprite/interface/button_menu/unselected_menu_middle.png", true);
		button_menu_unselected_top = new Texture("sprite/interface/button_menu/unselected_menu_top.png", true);
		frame_tab_active_left_part = new Texture("sprite/interface/frame_tab/active_left_part.png", true);
		frame_tab_active_middle_part = new Texture("sprite/interface/frame_tab/active_middle_part.png", true);
		frame_tab_active_right_part = new Texture("sprite/interface/frame_tab/active_right_part.png", true);
		frame_tab_inactive_left_part = new Texture("sprite/interface/frame_tab/inactive_left_part.png", true);
		frame_tab_inactive_middle_part = new Texture("sprite/interface/frame_tab/inactive_middle_part.png", true);
		frame_tab_inactive_right_part = new Texture("sprite/interface/frame_tab/inactive_right_part.png", true);
		discussion_frame = new Texture("sprite/interface/social/discussion_frame.png", false);
		return true;
	}

	public static boolean sprite10() {
		spellbar = new Texture("sprite/interface/spellbar.png", false);
		spriteLoaded = true;
		return true;
	}
	
	public static boolean getSpriteLoaded() {
		return spriteLoaded;
	}
}
