package com.mideas.rpg.v2.utils;

public enum UIElementType {

	FRAME,
	BUTTON,
	CROSS_BUTTON,
	EDIT_BOX,
	FRAME_TAB,
	LARGE_TEXT_DISPLAY,
	MAIL_INBOX_BUTTON,
	AUCTION_HOUSE_BROWSE_CATEGORY_FILTER_BUTTON,
	INPUT_BOX_CROSS_BUTTON,
	SORT_BUTTON,
	PREMADE_GROUP_CATEGORY_BUTTON,
	INPUT_BOX,
	
}
