package com.mideas.rpg.v2.hud.social.who;

public enum WhoSort {

	NAME_ASCENDING,
	NAME_DESCENDING,
	AREA_ASCENDING,
	AREA_DESCENDING,
	GUILD_ASCENDING,
	GUILD_DESCENDING,
	RACE_ASCENDING,
	RACE_DESCENDING,
	LEVEL_ASCENDING,
	LEVEL_DESCENDING,
	CLASSE_ASCENDING,
	CLASSE_DESCENDING
	
}
