package com.mideas.rpg.v2.game;

public enum PopupType {

	ADD_PARTY,
	ADD_GUILD,
	ADD_FRIEND,
	ADD_IGNORE,
	DELETE_ITEM,
	GUILD_INVITATION,
	PARTY_INVITATION,
	TRADE_REQUEST,
	GUILD_KICK_MEMBER,
	GUILD_SET_MEMBER_PUBLIC_NOTE,
	GUILD_SET_MEMBER_OFFICER_NOTE,
	NONE,
	
}
